### ISSUE TITLE
Error: Native-image building on Windows currently only supports target architecture: AMD64 (?? unsupported)

### ISSUE THREAD

**Issue by aomsweet** [oracle/graal#3122]
**Describe the issue**

```java

[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 20.3.0 (Java Version 11.0.9+10-jvmci-20.3-b06)

[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] V:\Java\graalvm-ce-java11-latest\bin\native-image.cmd -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.
util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.d
isableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=zh -J-Dfile.encoding=UTF-8 --initialize-at-bui
ld-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -jar eterm-sunstn-1.0.0-SNAPSHOT-runner.jar -H:Fallbac
kThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:-UseServiceLoaderFeature -H:+Stac
kTrace eterm-sunstn-1.0.0-SNAPSHOT-runner
[eterm-sunstn-1.0.0-SNAPSHOT-runner:13648]    classlist:   1,953.81 ms,  0.94 GB
[eterm-sunstn-1.0.0-SNAPSHOT-runner:13648]        setup:     613.00 ms,  0.94 GB
Error: Native-image building on Windows currently only supports target architecture: AMD64 (?? unsupported)
Error: To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
com.oracle.svm.core.util.UserError$UserException: Native-image building on Windows currently only supports target architecture: AMD64 (?? unsupported)
To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
        at com.oracle.svm.core.util.UserError.abort(UserError.java:139)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.addSkipCheckingInfo(CCompilerInvoker.java:105)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.verifyCompiler(CCompilerInvoker.java:96)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:870)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:556)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:471)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.593 s
[INFO] Finished at: 2021-01-13T12:08:53+08:00
[INFO] ------------------------------------------------------------------------

```

**Steps to reproduce the issue**

command:
```shell
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
```
![image](https://user-images.githubusercontent.com/70388114/104406094-77036300-5599-11eb-9f60-070f2af55d05.png)
![image](https://user-images.githubusercontent.com/70388114/104406105-7ff43480-5599-11eb-8ad2-37296a6a2495.png)

```shell
mvn clean package -Dmaven.test.skip=true -Pnative
```

**Describe GraalVM and your environment:**
 - GraalVM version: GraalVM11-CE-20.3.0
 - JDK major version: 11
 - OS: Windows 10x64 pro 2004 19041.685
 - Architecture: AMD64
 - Visual Studio: 2019-Community
 - Quarkus: 1.10.5.Final

**Comment by olpaw** [comment]
A quick check on Windows shows that image building should work fine
```
Microsoft Windows [Version 11.0.19042.685]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\paulw>"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.8.4
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Users\paulw>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29336 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

C:\Users\paulw>native-image --version
GraalVM Version 20.3.0 (Java Version 11.0.9+10-jvmci-20.3-b06)

C:\Users\paulw>native-image -jar "%JAVA_HOME%\lib\graalvm\svm-driver.jar"
[native-image:11588]    classlist:   1,631.31 ms,  0.96 GB
[native-image:11588]        (cap):   2,763.47 ms,  0.96 GB
[native-image:11588]        setup:   4,475.12 ms,  0.96 GB
[native-image:11588]     (clinit):     419.65 ms,  2.30 GB
[native-image:11588]   (typeflow):  11,900.80 ms,  2.30 GB
[native-image:11588]    (objects):   9,431.64 ms,  2.30 GB
[native-image:11588]   (features):     533.81 ms,  2.30 GB
[native-image:11588]     analysis:  22,761.80 ms,  2.30 GB
[native-image:11588]     universe:     836.77 ms,  2.30 GB
[native-image:11588]      (parse):   2,956.14 ms,  2.30 GB
[native-image:11588]     (inline):   2,101.22 ms,  2.30 GB
[native-image:11588]    (compile):  20,915.45 ms,  4.12 GB
[native-image:11588]      compile:  27,106.17 ms,  4.12 GB
[native-image:11588]        image:   2,198.07 ms,  4.12 GB
[native-image:11588]        write:     538.87 ms,  4.12 GB
[native-image:11588]      [total]:  59,774.04 ms,  4.12 GB
```
To reproduce your issue you need to provide detailed information what you are building with maven. (E.g. the repository/repositories that I have to check out before I run `mvn clean package -Dmaven.test.skip=true -Pnative`)

Please provide the full output when using native-image option `-H:+TraceNativeToolUsage` in your image building? This will show exactly what `cl.exe` gets used here and what output it produces.

**Comment by aomsweet** [comment]
@olpaw hi.
`?? unsupported`  Unable to identify the operating system version?

**Comment by olpaw** [comment]
> ?? unsupported Unable to identify the operating system version?

No. That means unable to identify for which target platform your `cl.exe` builds executables for.
If your your Visual Studio was installed with some uncommon language settings that might be the problem.

What output do you get when you run
```
native-image -H:+TraceNativeToolUsage -jar "%JAVA_HOME%\lib\graalvm\svm-driver.jar"
```
in the `Visual Studio 2019 Developer Command Prompt`?

**Comment by aomsweet** [comment]
@olpaw  Hi.

As you said, the cause of this error is my locale, I can successfully create native-image by switching to English.

Thank you very much.  ☕

**Comment by SetoKaiba** [comment]
@olpaw I encounter this problem as well. I can't build even with system language English.
I call cl.exe in terminal. The cl.exe output is still in Chinese.

> 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30133 版
> 版权所有(C) Microsoft Corporation。保留所有权利。
> 
> 用法: cl [ 选项... ] 文件名... [ /link 链接选项... ]

**Comment by petermz** [comment]
You can change the language cl.exe speaks using Visual Studio Installer. I don't have Windows around at the moment, but it should have "Language Packs" tab somewhere, where you uncheck Chinese and check English. No restart needed

**Comment by cms88168** [comment]
There is an easy way to get this around with,simply use `-H:-CheckToolchain` as an option when building.

**Comment by aomsweet** [comment]
Hi, @cms88168  Thanks, I will try your suggestion.

**Comment by LaiZhou** [comment]
Would this bug be fixed in future ? It's not friendly for non-english developer.

**Comment by kim-zach** [comment]
![image](https://user-images.githubusercontent.com/86898876/180597886-8b5c2d87-20bd-462a-b36a-0747e7da04d9.png)

hi what is this possibly about ?

**Comment by rffanlab** [comment]
> From China. Recently I get this problem and workaround by 2 steps below:
> 
> 1. Install Visual Studio 2022 in English.
> 2. Run native-image in "x64 Native Tools Command Prompt for VS 2022" which is installed with Visual Studio.
> 
> Root-cause guessing (only guessing because I have not learnt how to debug graalvm yet :P ): In `com.oracle.svm.hosted.c.codegen.CComplierInvoker$WindowsCCompilerInvoker#createCompilerInfo() `, I saw Paul and Filip had kindly added some code pieces to handle output of cl.exe in simplified Chinese in UTF-8. However, Windows 10 simplified Chinese version is running in a default code page 936, and this means the default encode of OS is GB2312 rather than UTF-8. Surely, I can set the code page to 65001 which means UTF-8 in Windows, but this will make zip file extracted with messy filename when the zip file is compressed and uncompressed by two computers with different code page.
> 
> BTW, the code page can be changed by the command chcp, or by the Locale set. As the figure below, with the checkbox ticked off, you will get the code page 936, or 65001 with it ticked on. ![image](https://user-images.githubusercontent.com/13246803/210746763-951d7187-141c-4108-9693-3950493bc64b.png)

这个可以，我这样设置后也能编译通过了。

**Comment by WangMinan** [comment]
补充一点，在使用visual studio生成工具的时候记得把语言包换成英语 https://blog.csdn.net/qq_44732146/article/details/128877947
In addition, when using the visual studio generation tool, remember to change the language pack to English.

**Comment by GangLiCN** [comment]
1) The language of visual studio installer is alread English, see the output of "cl.exe":
###
Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33522 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
###

2) But, unfortunately, this issue is still reproduced in Graalvm for Java17 and java21.

java -version
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment GraalVM CE 22.3.3 (build 17.0.8+7-jvmci-22.3-b22)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.3 (build 17.0.8+7-jvmci-22.3-b22, mixed mode, sharing)


3) The output snippet of "mvn clean package -Pnative -DskipTests":
......
========================================================================================================================
GraalVM Native Image: Generating 'native-app' (executable)...
========================================================================================================================

[1/7] Initializing...                                                                                    (0.0s @ 0.26GB)
Error: Native-image building on Windows currently only supports target architecture: AMD64 (32-bit architecture x86 unsupported)
Error: To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
......

Any good ideas  ?

**Comment by GangLiCN** [comment]
Fixed this issue by referring above-mentioned "tip":
1) Open "X64 Native tools command prompt for Visual Studio xxxx"
## Note that for Graalvm-jdk21, you must use Visual Studio 2022.

2) Execute "chcp 65001" to change code page to UTF-8;
## This is must to do, otherwise you'll still hit this issue.

3)  Build native application via  "mvn clean package -Pnative -DskipTests" 
## Do not use "mvn native:compile" since it will introduce another native-maven-plugin bug:
(Can not recognize backslash as the dir separator on windows...)

**Comment by ghotm** [comment]
> There is an easy way to get this around with,simply use `-H:-CheckToolchain` as an option when building.

I used this configuration, and it is working.

```
<plugin>
  <groupId>org.graalvm.buildtools</groupId>
  <artifactId>native-maven-plugin</artifactId>
  <configuration>
	  <skip>false</skip>
	  <buildArgs>
		  -H:-CheckToolchain
		  --no-fallback
		  --initialize-at-build-time=ch.qos.logback
		  --initialize-at-build-time=org.slf4j
	  </buildArgs>
	  <mainClass>me.toolkit.xxx.xxx.xxxApplication</mainClass>
  </configuration>
</plugin>
```
